# File: docker/Dockerfile.db
# Minimal PostgreSQL for BMI Calculator

FROM postgres:12-alpine

# Set environment variables
ENV POSTGRES_DB=bmi_calculator
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=psswd

EXPOSE 5432